// 🔥 TEMP SAMPLE DATA (UI testing)
const vehiclesData = [
  {
    id: "VH001",
    name: "Tesla Model 3",
    driver: "John Smith",
    lat: 28.7041,
    lng: 77.1025,
    speed: 45,
    status: "moving",
    lastUpdate: "2 min ago",
  },
  {
    id: "VH002",
    name: "Toyota Camry",
    driver: "Amit Kumar",
    lat: 28.5355,
    lng: 77.3910,
    speed: 0,
    status: "idle",
    lastUpdate: "5 min ago",
  },
  {
    id: "VH003",
    name: "Honda Accord",
    driver: "Priya Sharma",
    lat: 28.4595,
    lng: 77.0266,
    speed: 22,
    status: "moving",
    lastUpdate: "1 min ago",
  },
  {
    id: "VH004",
    name: "Mahindra XUV700",
    driver: "Rahul Verma",
    lat: 28.4089,
    lng: 77.3178,
    speed: 0,
    status: "stopped",
    lastUpdate: "8 min ago",
  },
  {
    id: "VH005",
    name: "Hyundai Creta",
    driver: "Sneha Reddy",
    lat: 28.6139,
    lng: 77.2090,
    speed: 38,
    status: "moving",
    lastUpdate: "Just now",
  },
];